//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUTH_USER
    {
        public decimal IDAUT { get; set; }
        public string USERNAME { get; set; }
        public string PASSWORD { get; set; }
        public Nullable<decimal> USUARIO_CLIENTE_IDUSU { get; set; }
        public Nullable<decimal> USUARIO_SISTEMA_IDSIS { get; set; }
    
        public virtual USUARIO_CLIENTE USUARIO_CLIENTE { get; set; }
        public virtual USUARIO_SISTEMA USUARIO_SISTEMA { get; set; }
    }
}
