//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUTH_USUARIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AUTH_USUARIO()
        {
            this.USUARIO1 = new HashSet<USUARIO>();
            this.USUARIO_SISTEMA1 = new HashSet<USUARIO_SISTEMA>();
        }
    
        public decimal ID_AUTH { get; set; }
        public string USERNAME { get; set; }
        public string PASSWORD { get; set; }
        public string USUARIO_ID_USER { get; set; }
        public Nullable<decimal> USUARIO_SISTEMA_ID { get; set; }
    
        public virtual USUARIO_SISTEMA USUARIO_SISTEMA { get; set; }
        public virtual USUARIO USUARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USUARIO> USUARIO1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USUARIO_SISTEMA> USUARIO_SISTEMA1 { get; set; }
    }
}
