//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCUMENTO
    {
        public decimal ID { get; set; }
        public byte[] ARCHIVO { get; set; }
        public Nullable<decimal> EMPRESA_IDEMP { get; set; }
    
        public virtual EMPRESA EMPRESA { get; set; }
    }
}
