//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERROR_TAREA
    {
        public decimal IDERR { get; set; }
        public string JUSTIFICACION { get; set; }
        public System.DateTime FECHA { get; set; }
        public Nullable<decimal> TAREA_IDTAR { get; set; }
    
        public virtual TAREA TAREA { get; set; }
    }
}
