//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class FLUJO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FLUJO()
        {
            this.HISTORIAL_FLUJOS = new HashSet<HISTORIAL_FLUJOS>();
        }
    
        public decimal ID_FRUJO { get; set; }
        public string NOMBRE { get; set; }
        public System.DateTime EJECUCION { get; set; }
        public decimal ESTADO_FLUJO_ID { get; set; }
        public string DESCRIPCION { get; set; }
        public string USUARIO_ID_USER { get; set; }
        public Nullable<decimal> USUARIO_SISTEMA_ID { get; set; }
    
        public virtual ESTADO_FLUJO ESTADO_FLUJO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
        public virtual USUARIO_SISTEMA USUARIO_SISTEMA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HISTORIAL_FLUJOS> HISTORIAL_FLUJOS { get; set; }
    }
}
