//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class FLUJO_INSTANCIA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FLUJO_INSTANCIA()
        {
            this.TAREA_INSTANCIA = new HashSet<TAREA_INSTANCIA>();
        }
    
        public decimal ID { get; set; }
        public System.DateTime INICIO { get; set; }
        public decimal PLANTILLA_ID { get; set; }
        public decimal ESTADO_ID { get; set; }
        public System.DateTime FIN { get; set; }
        public decimal RESPONSABLE { get; set; }
    
        public virtual ESTADO_FLUJO ESTADO_FLUJO { get; set; }
        public virtual FLUJO FLUJO { get; set; }
        public virtual USUARIO_CLIENTE USUARIO_CLIENTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAREA_INSTANCIA> TAREA_INSTANCIA { get; set; }
    }
}
