//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class HISTORIAL_TAREA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HISTORIAL_TAREA()
        {
            this.TAREA1 = new HashSet<TAREA>();
        }
    
        public decimal ID { get; set; }
        public string DESCRIPCION { get; set; }
        public System.DateTime FECHA_TERMINO { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
        public decimal TAREA_ID_TAREA { get; set; }
    
        public virtual TAREA TAREA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAREA> TAREA1 { get; set; }
    }
}
