//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AUTH_USUARIO> AUTH_USUARIO { get; set; }
        public virtual DbSet<DEPARTAMENTO> DEPARTAMENTO { get; set; }
        public virtual DbSet<DOCUMENTOS> DOCUMENTOS { get; set; }
        public virtual DbSet<EMPRESA> EMPRESA { get; set; }
        public virtual DbSet<ERROR_TAREA> ERROR_TAREA { get; set; }
        public virtual DbSet<ERRORES> ERRORES { get; set; }
        public virtual DbSet<ESTADO_FLUJO> ESTADO_FLUJO { get; set; }
        public virtual DbSet<ESTADO_USUARIO> ESTADO_USUARIO { get; set; }
        public virtual DbSet<ESTADOTAREA> ESTADOTAREA { get; set; }
        public virtual DbSet<FLUJO> FLUJO { get; set; }
        public virtual DbSet<HISTORIAL_FLUJOS> HISTORIAL_FLUJOS { get; set; }
        public virtual DbSet<HISTORIAL_TAREA> HISTORIAL_TAREA { get; set; }
        public virtual DbSet<ROL_CLIENTE> ROL_CLIENTE { get; set; }
        public virtual DbSet<ROL_SISTEMA> ROL_SISTEMA { get; set; }
        public virtual DbSet<SEXO> SEXO { get; set; }
        public virtual DbSet<TAREA> TAREA { get; set; }
        public virtual DbSet<USUARIO> USUARIO { get; set; }
        public virtual DbSet<USUARIO_SISTEMA> USUARIO_SISTEMA { get; set; }
    }
}
