//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAREA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TAREA()
        {
            this.ERROR_TAREA = new HashSet<ERROR_TAREA>();
            this.HISTORIAL_TAREA = new HashSet<HISTORIAL_TAREA>();
            this.TAREA1 = new HashSet<TAREA>();
        }
    
        public decimal ID_TAREA { get; set; }
        public string DESCRIPCION { get; set; }
        public System.DateTime COMIENZO { get; set; }
        public System.DateTime TERMINO { get; set; }
        public string JUSTIFICACION { get; set; }
        public decimal ESTADOTAREA_ID { get; set; }
        public string USUARIO_ID_USER { get; set; }
        public decimal TAREA_ID_TAREA { get; set; }
        public Nullable<decimal> USUARIO_SISTEMA_ID { get; set; }
        public decimal HISTORIAL_TAREA_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ERROR_TAREA> ERROR_TAREA { get; set; }
        public virtual ESTADOTAREA ESTADOTAREA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HISTORIAL_TAREA> HISTORIAL_TAREA { get; set; }
        public virtual HISTORIAL_TAREA HISTORIAL_TAREA1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAREA> TAREA1 { get; set; }
        public virtual TAREA TAREA2 { get; set; }
        public virtual USUARIO USUARIO { get; set; }
        public virtual USUARIO_SISTEMA USUARIO_SISTEMA { get; set; }
    }
}
