//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAREA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TAREA()
        {
            this.ERROR_TAREA = new HashSet<ERROR_TAREA>();
            this.FLUJO = new HashSet<FLUJO>();
            this.TAREA1 = new HashSet<TAREA>();
            this.TAREA2 = new HashSet<TAREA>();
            this.USUARIO_CLIENTE = new HashSet<USUARIO_CLIENTE>();
        }
    
        public decimal IDTAR { get; set; }
        public string DESCRIPCION { get; set; }
        public System.DateTime INICIO { get; set; }
        public System.DateTime FIN { get; set; }
        public decimal DURACION { get; set; }
        public Nullable<decimal> ESTADO_TAREA_IDEST { get; set; }
        public Nullable<decimal> CARGOS_IDDEP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ERROR_TAREA> ERROR_TAREA { get; set; }
        public virtual ESTADO_TAREA ESTADO_TAREA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FLUJO> FLUJO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAREA> TAREA1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAREA> TAREA2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USUARIO_CLIENTE> USUARIO_CLIENTE { get; set; }
        public virtual CARGOS CARGOS { get; set; }
    }
}
