//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO_SISTEMA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USUARIO_SISTEMA()
        {
            this.AUTH_USER = new HashSet<AUTH_USER>();
        }
    
        public decimal IDSIS { get; set; }
        public string NOMBRE { get; set; }
        public string APELLIDO { get; set; }
        public string CORREO { get; set; }
        public Nullable<decimal> ESTADO_USUARIO_IDESU { get; set; }
        public Nullable<decimal> SEXO_IDSEX { get; set; }
        public Nullable<decimal> ROL_SISTEMA_IDROS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AUTH_USER> AUTH_USER { get; set; }
        public virtual ESTADO_USUARIO ESTADO_USUARIO { get; set; }
        public virtual ROL_SISTEMA ROL_SISTEMA { get; set; }
        public virtual SEXO SEXO { get; set; }
    }
}
